language: go
go:
  - 1.6

sudo: false

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

before_install:
  - go get github.com/vbatts/git-validation
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install --update
  - go get -t -d ./...

install: true

script:
  - git-validation -run DCO,short-subject -v -range ${TRAVIS_COMMIT_RANGE}
  - make lint
  - make check-license
  - make test
  - make oci-image-tool
