language: go
go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

sudo: required

services:
  - docker

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

before_install:
  - docker pull quay.io/oci/pandoc:1.17.0.3-2.fc25.x86_64
  - make install.tools
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - go get -t -d ./...

install: true

script:
  - env | grep TRAVIS_
  - make .gitvalidation
  - make lint
  - make check-license
  - make test
  - make docs
